# Generated by Django 5.1 on 2024-08-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_users_delete_user_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
