# Generated by Django 5.1 on 2024-08-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_rename_user_name_users_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='user_data',
        ),
    ]
